### ISSUE TITLE
master copies

### ISSUE THREAD

**Issue by benj-d** [Indicia-Team/drupal-7-module-iform#4]
The D7 iform module master links through to 'non master' media and client helper sub modules. Are these good to use/the actual master versions?

**Comment by johnvanbreda** [comment]
Hi Ben

The master branches of client_helpers and media are quite out of date and about to be updated. Since the master branch is about to be merged into from the release-1.0.0 branch (which is a release candidate) you might like to use release-1.0.0 instead? As far as I am aware the links to the submodules should be correct then.

Cheers

John
